#
# CppPotpourri build defs for ESP-IDF 
#

COMPONENT_ADD_INCLUDEDIRS := $(PROJECT_PATH)/src .

CFLAGS += -D__MANUVR_ESP32
CXXFLAGS += -D__MANUVR_ESP32

LOCAL_ESP_COMPS += $(PROJECT_PATH)/src $(PROJECT_PATH)/src/cbor-cpp $(PROJECT_PATH)/src/Image

COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := $(LOCAL_ESP_COMPS)
