name: TestCovAndDoc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # This library is most-commonly run on 32-bit targets. So we need to put together
    #   a GCC environment that supports it.
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x86
    - name: Install tools
      run: sudo apt install -y cppcheck lcov graphviz doxygen
    - name: make
      run: cd extras/unit_tests; make alltests check
    - name: package-results
      run: cd cd extras/unit_tests/build; tar -cvf ../../../test-cov-doc.tar .
    - uses: actions/upload-artifact@v4
      with:
        name: results
        path:  test-cov-doc.tar
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false


